# Generated by Django 3.2.6 on 2021-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_extendeduser_reciver'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_blood_bank',
            field=models.BooleanField(default=False),
        ),
    ]
